# Generated by Django 2.2.5 on 2021-05-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
